"""
Django settings for impeachment_webservice project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$q7f9g+%-rn+7#b^c&#skb+2f$47tf1$691l#u9e043gty*r&h"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "impeachment",
    "rest_framework",
    "drf_yasg",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "impeachment_webservice.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "impeachment_webservice.wsgi.application"


# CONFIGURATTION REDOC AND SWAGGER
REDOC_SETTINGS = {
    "HIDE_HOSTNAME": True,
    "EXPAND_RESPONSES": "all",
    "no-auto-auth": True,
}

SWAGGER_SETTINGS = {
    "USE_SESSION_AUTH": False,
    "SECURITY_DEFINITIONS": {},
    "VALIDATOR_URL": "",
    "OPERATIONS_SORTER": "method",
    "TAGS_SORTER": None,
    "DOC_EXPANSION": "list",
    "DEEP_LINKING": False,
    "SHOW_EXTENSIONS": True,
    "DEFAULT_INFO": "config.docs.swagger_info",
    "DEFAULT_MODEL_RENDERING": "model",
    "DEFAULT_MODEL_DEPTH": 2,
}


# CONFIGURATION DJANGO-REST-FRAMEWORK
#REST_FRAMEWORK = {
#    "UNAUTHENTICATED_USER": None,
#    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
#    "DEFAULT_AUTHENTICATION_CLASSES": [
#        "common.rest_framework.keycloak_authentication.KeycloakAuthentication"
#    ],
#    "PAGE_SIZE": 100,
#    "ORDERING_PARAM": "order",
#}


# CONFIGURATION KEYCLOAK
KEYCLOAK_PUBLIC_KEY = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsFHdqPiyJHhE3YM0fD9J25ryICcC4PgraVAF0KtnM4ZUUc6g5gimdqubwJqX7ttmePLXVx1P0yOhYIxUtm2UQ/mTrpBn6GMotrMX12bWiQ7V6oDV/r0HMBEjxohmWR6HtGmq31DhZtMr8BTPBb9REiVKCMnIs1q2QuT/5vk3HRfGxeSkFcaigXjioVXlPnY8zcfS5QtFCJOkvaXDRcwIsoPs4zvQo7EOKizt+zSs59jwANky3I+obECMb0/V7ButqFVkYpD8vMlewYIigjcEA//ABB0pvO5dHcSvL9BmG5rbLcDTzHXerjyd+FKvzAL46GcTDMHeFBb0lx6xznDDowIDAQAB"

KEYCLOAK_FORMAT_PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
{}
-----END PUBLIC KEY-----"""

KEYCLOAK_SERVER_URL = "https://keycloak-dev.camposdevelopers.com.br/auth/"
KEYCLOAK_REALM = "campos_developers"
KEYCLOAK_CLIENT_ID = "impeachment"
KEYCLOAK_CLIENT_SECRET_KEY = "ookUhqBU70vU8XiYy65QS2vlec9IxSAg"

KEYCLOAK_CLIENT_PUBLIC_KEY = {
    "KEYCLOAK_CLIENT_PUBLIC_KEY": KEYCLOAK_PUBLIC_KEY
}

KEYCLOAK_CONFIG = {
    "KEYCLOAK_SERVER_URL": KEYCLOAK_SERVER_URL,
    "KEYCLOAK_REALM": KEYCLOAK_REALM,
    "KEYCLOAK_CLIENT_ID": KEYCLOAK_CLIENT_ID,
    "KEYCLOAK_CLIENT_SECRET_KEY": KEYCLOAK_CLIENT_SECRET_KEY,
    "KEYCLOAK_CLIENT_PUBLIC_KEY": KEYCLOAK_FORMAT_PUBLIC_KEY.format(
        KEYCLOAK_CLIENT_PUBLIC_KEY
    ),
}


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
