"""
Django urls for inventoryimpeachment project.

Generated by 'kawe-henrique'
Date_create: 21/03/2023

this urls file is a set of the patterns that Django will use to compare against the incoming URL to find the correct answer.
in the case of this project, we create urls for each views.
"""


from django.contrib import admin
from django.urls import path
from impeachment.views import ImpeachmentCreateViewSet
from impeachment.views import ImpeachmentRetrieveUpdateDeleteViewSet
from impeachment.views import ImpeachmentListViewSet
from impeachment.views import RequestTestAPI
from .docs import schema_view

urlpatterns = [
    path("api/v1/Impeachments/create", ImpeachmentCreateViewSet.as_view(), name="Impeachment_create"),

    path("api/v1/Impeachments/<int:pk>/retrieve", ImpeachmentRetrieveUpdateDeleteViewSet.as_view(), name = "Impeachment_retrieve"),

    path("api/v1/Impeachments/<int:pk>/update", ImpeachmentRetrieveUpdateDeleteViewSet.as_view(), name = "Impeachment_update"),

    path("api/v1/Impeachments/<int:pk>/destroy", ImpeachmentRetrieveUpdateDeleteViewSet.as_view, name = "Impeachment_destroy"),

    path("api/v1/Impeachments/list", ImpeachmentListViewSet.as_view, name = "Impeachment_list"),

    path("api/v1/request", RequestTestAPI.as_view(), name = "Impeachment_test"),   
    path("docs/", schema_view.with_ui ("swagger", cache_timeout=None), name= "schema-swagger-ui"),
    path("redoc/", schema_view.with_ui ("redoc", cache_timeout=None), name= "schema-redoc")
]