"""
Django serializers for Impeachment app.

Generated by 'kawe-henrique'
date_create: 21/03/2023

this serilizer file has the function of converting complex data (in our case the rest_framework and the models)
the native Python data types that can be easily rendered in JSON,XML or other types of content.
"""

from rest_framework import serializers
from impeachment.models import Impeachment


class ImpeachmentSerializers(serializers.ModelSerializer):
    """
    A 'serializer' of 'Impeachment',With Function:
    '* serializer Data: Transform Object to Data.
    '* Deserializer Data: Transform Data to Object.
    """

    class Meta:
        model = Impeachment
        fields = "__all__"
