"""
Django views for Impeachment app.

Generated by 'kawe-henrique'
Date_create: 21/03/2023

this views file is where we put the 'logic' of our application.
It will extract information from the model you created and deliver it to a template.
"""

from django.shortcuts import render
from rest_framework import generics
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializers import ImpeachmentSerializers
from .models import Impeachment


class RequestTestAPI(APIView):
    """View to Check if API is working"""

    def get(self, request, format=None):
        return Response({"API": "OK"})


class ImpeachmentCreateViewSet(generics.CreateAPIView):
    """Create Product with Method: 'POST'"""

    queryset = Impeachment.objects.all()
    serializer_class = ImpeachmentSerializers
    """Update/Delete/Retrieve Product with one these Method: 'GET' / 'UPDATE' / 'DELETE'"""


class ImpeachmentRetrieveUpdateDeleteViewSet(generics.RetrieveUpdateDestroyAPIView):

    queryset = Impeachment.objects.all()
    serializer_class = ImpeachmentSerializers


class ImpeachmentListViewSet(generics.ListAPIView):
    """View to List all Product with Method: 'GET'"""

    queryset = Impeachment.objects.all()
    serializer_class = ImpeachmentSerializers
